apiVersion: v1
kind: Service
metadata:
  name: js-client-svc
  labels:
    app: js-client
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: js-client