apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-client
  labels:
    app: js-client
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-client
  template:
    metadata:
      labels:
        app: js-client
    spec:
      containers:
      - name: js-client
        image: registry.gitlab.com/heigvd-software-engineering/grpc-example/js-client
        ports:
        - containerPort: 80