apiVersion: v1
kind: Service
metadata:
  name: envoy-svc
  labels:
    app: envoy
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: client
    port: 8080
    targetPort: 8080
  selector:
    app: envoy