apiVersion: v1
kind: Service
metadata:
  name: java-server-svc
  labels:
    app: java-server
    tier: api
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: java-server