apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server
  labels:
    app: java
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: myimage
        ports:
        - containerPort: 80