apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server
  labels:
    app: java-server
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-server
  template:
    metadata:
      labels:
        app: java-server
    spec:
      containers:
      - name: java-server
        image: registry.gitlab.com/heigvd-software-engineering/grpc-example/java-server
        ports:
        - containerPort: 9090